Repository dimagi/formplayer, pull requests merged in 2019-11, with the labels that each got.

#696 Document and flesh out rebuildstaging workflow
  .gitignore
  scripts/rebuildstaging
  scripts/rebuildstaging-requirements.txt
  scripts/rebuildstaging.py
  scripts/sh_verbose.py
  scripts/staging.yaml
Labels: product/invisible

#697 Add HQ request timeouts (second try)
  src/main/java/application/WebAppContext.java
  src/main/java/services/RestoreFactory.java
  src/main/java/util/Constants.java
  src/test/java/utils/TestContext.java
Labels: bug, product/invisible

#699 spring managed flyway with default config
  src/main/java/application/Application.java
  src/main/resources/application.properties
Labels: product/invisible

#701 Lock in Gradle dependency versions for modernized Spring libs
  build.gradle
  src/main/java/sandbox/SqlHelper.java
  src/main/java/sqlitedb/SQLiteDB.java
Labels: open for review, product/invisible

#700 let spring manage the DB datasource
  .travis/application.example.properties
  config/application.docker.properties
  config/application.example.properties
  src/main/java/application/WebAppContext.java
  src/main/resources/application.properties
Labels: product/invisible

#703 support redis password
  .travis/application.example.properties
  config/application.docker.properties
  config/application.example.properties
  src/main/java/application/WebAppContext.java
Labels: product/invisible

#704 Clear the userDB and retry when we get a 412 on restore
  src/main/java/application/WebAppContext.java
  src/main/java/services/RestoreFactory.java
  src/test/java/utils/TestContext.java
Labels: product/all-users

#689 Use bucket counter instead of datadog histogram for restore timing
  src/main/java/services/RestoreFactory.java
  src/main/java/util/Constants.java
  src/main/java/util/Timing.java
Labels: enhancement, product/invisible

#705 Update Sentry dependence
  build.gradle
Labels: product/invisible

#706 Modernize Database Connection Management
  src/main/java/database/models/EntityStorageCache.java
  src/main/java/database/models/FormplayerCaseIndexTable.java
  src/main/java/sandbox/ArchivableFile.java
  src/main/java/sandbox/JdbcSqlStorageIterator.java
  src/main/java/sandbox/SqlHelper.java
  src/main/java/sandbox/SqlStorage.java
  src/main/java/sandbox/UserSqlSandbox.java
  src/main/java/services/FormplayerStorageFactory.java
  src/main/java/services/RestoreFactory.java
  src/main/java/sqlitedb/SQLiteDB.java
Labels: open for review, product/invisible

#707 Fix Issues with Dangling DB Connections
  src/main/java/sandbox/SqlSandboxUtils.java
Labels: bug, open for review, product/invisible
