Repository dimagi/formplayer, pull requests merged in 2020-05, with the labels that each got.

#720 Update Aggressive Sync times
  src/main/java/services/RestoreFactory.java
Labels: product/feature-flag

#719 Exposing Error Notifications to Sentry
  src/main/java/application/AbstractBaseController.java
  src/main/java/application/DebuggerController.java
  src/main/java/application/FormController.java
  src/main/java/application/IncompleteSessionController.java
  src/main/java/application/MenuController.java
  src/main/java/application/UtilController.java
  src/main/java/beans/NotificationMessage.java
  src/main/java/beans/menus/BaseResponseBean.java
  src/main/java/objects/FormVolatilityRecord.java
  src/main/java/services/InstallService.java
  src/main/java/services/MenuSessionRunnerService.java
  src/main/java/session/MenuSession.java
  src/main/java/util/Constants.java
Labels: product/invisible

#721 Use time in seconds for getDurationBucket method call
  src/main/java/aspects/MetricsAspect.java
  src/main/java/util/SimpleTimer.java
Labels: product/invisible

#724 Include origin token in restore requests
  src/main/java/application/WebAppContext.java
  src/main/java/services/RestoreFactory.java
  src/test/java/utils/TestContext.java
Labels: product/invisible

#725 Signal 401 on Unavailable Session
  src/main/java/application/FormplayerAuthFilter.java
  src/main/java/exceptions/SessionAuthUnavailableException.java
  src/main/java/services/HqUserDetailsService.java
Labels: product/invisible

#723 Enable fuzzy search
  src/main/java/application/MenuController.java
  src/main/java/beans/menus/EntityDetailListResponse.java
  src/main/java/beans/menus/EntityDetailResponse.java
  src/main/java/beans/menus/EntityListResponse.java
  src/main/java/services/MenuSessionRunnerService.java
  src/main/java/util/EntityStringFilterer.java
  src/main/java/util/FormplayerPropertyManager.java
  src/test/java/mocks/FormPlayerPropertyManagerMock.java
  src/test/java/tests/CasePaginationTests.java
Labels: open for review, product/all-users
