Repository dimagi/formplayer, pull requests merged in 2020-07, with the labels that each got.

#736 request logging
  build.gradle
  src/main/java/org/commcare/formplayer/application/Application.java
  src/main/java/org/commcare/formplayer/application/FormplayerAuthFilter.java
  src/main/java/org/commcare/formplayer/application/RequestResponseLoggingFilter.java
  src/test/java/tests/RequestResponseLoggingFilterTest.java
Labels: product/invisible

#751 Remove aggression from in-form requests
  src/main/java/org/commcare/formplayer/services/RestoreFactory.java
  src/main/java/org/commcare/formplayer/session/FormSession.java
Labels: enhancement, product/feature-flag

#750 Allow for 412 recovery in aggressive/timed out syncs
  src/main/java/org/commcare/formplayer/services/RestoreFactory.java
Labels: bug, product/all-users

#752 Fix duplicate restore timings
  config/application.example.properties
  src/main/java/org/commcare/formplayer/services/CategoryTimingHelper.java
  src/main/java/org/commcare/formplayer/services/RestoreFactory.java
Labels: product/invisible
