Repository dimagi/formplayer, pull requests merged in 2020-09, with the labels that each got.

#759 Added vim *.swp files to .gitignore
  .gitignore
Labels: product/invisible

#761 Kev/scheduled tasks
  build.gradle
  src/main/java/org/commcare/formplayer/application/WebAppContext.java
  src/main/java/org/commcare/formplayer/db/migration/V18__init_shedlock.java
  src/main/java/org/commcare/formplayer/repo/FormSessionRepo.java
  src/main/java/org/commcare/formplayer/repo/impl/PostgresFormSessionRepo.java
  src/main/java/org/commcare/formplayer/services/ScheduledTasks.java
  src/main/java/org/commcare/formplayer/util/Constants.java
  src/main/resources/application.properties
Labels: product/all-users, product/invisible

#763 change purge task default schedule to midnight
  src/main/java/org/commcare/formplayer/services/ScheduledTasks.java
Labels: product/all-users, product/invisible

#764 Add local.properties to ignore
  .gitignore
Labels: product/invisible

#765 Add Source ID to Request Logs
  src/main/java/org/commcare/formplayer/application/RequestResponseLoggingFilter.java
Labels: product/invisible

#766 Fix inconsistent test failures
  src/test/java/org/commcare/formplayer/tests/BaseTestClass.java
  src/test/java/org/commcare/formplayer/tests/CaseClaimTests.java
  src/test/java/org/commcare/formplayer/tests/CaseDbIndexTests.java
  src/test/java/org/commcare/formplayer/tests/CaseDbModelQueryTests.java
  src/test/java/org/commcare/formplayer/tests/CaseDbOptimizationsTest.java
  src/test/java/org/commcare/formplayer/tests/CaseDbQueryTest.java
  src/test/java/org/commcare/formplayer/tests/CasePaginationTests.java
  src/test/java/org/commcare/formplayer/tests/CaseTests.java
  src/test/java/org/commcare/formplayer/tests/FilterTests.java
  src/test/java/org/commcare/formplayer/tests/ReassignCaseTest.java
  src/test/java/org/commcare/formplayer/tests/SubmitTests.java
  src/test/java/org/commcare/formplayer/tests/sandbox/SqlStorageIndexedTests.java
  src/test/java/org/commcare/formplayer/tests/sandbox/UserSqlSandboxTest.java
Labels: product/invisible

#767 skip fixtures
  src/main/java/org/commcare/formplayer/application/FormController.java
  src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
  src/main/java/org/commcare/formplayer/services/NewFormResponseFactory.java
  src/main/java/org/commcare/formplayer/services/RestoreFactory.java
  src/main/java/org/commcare/formplayer/util/FormplayerPropertyManager.java
  src/test/java/org/commcare/formplayer/tests/BaseTestClass.java
  src/test/java/org/commcare/formplayer/tests/CaseClaimTests.java
Labels: product/invisible

#758 change form language
  src/main/java/org/commcare/formplayer/application/FormController.java
  src/main/java/org/commcare/formplayer/repo/impl/PostgresFormSessionRepo.java
Labels: product/invisible

#760 Added appearance attribute to json representation of groups
  src/main/java/org/commcare/formplayer/api/json/PromptToJson.java
Labels: product/all-users
