Repository dimagi/formplayer, pull requests merged in 2020-06, with the labels that each got.

#728 Ensure Sentry async connections are closed on cleanup
  src/main/java/application/WebAppContext.java
  src/main/java/util/FormplayerSentry.java
Labels: bug, product/invisible

#729 Catch Errors in Auth Filter
  src/main/java/application/FormplayerAuthFilter.java
  src/main/java/application/WebAppContext.java
  src/main/java/services/FallbackSentryReporter.java
Labels: product/invisible

#737 Update Error Reporting Paths
  src/main/java/application/AbstractBaseController.java
  src/main/java/application/DebuggerController.java
  src/main/java/application/MenuController.java
  src/main/java/application/UtilController.java
  src/main/java/beans/EvaluateXPathResponseBean.java
  src/main/java/beans/NotificationMessage.java
  src/main/java/exceptions/ApplicationConfigException.java
  src/main/java/services/MenuSessionRunnerService.java
Labels: product/invisible

#738 Improved Locking Pattern for Archivable Files
  src/main/java/exceptions/SqlArchiveLockException.java
  src/main/java/sandbox/ArchivableFile.java
  src/main/java/sandbox/SqlSandboxUtils.java
Labels: bug, product/invisible

#739 Document rebuildstaging
  scripts/staging.md
Labels: product/invisible

#742 Fix submit error reporting and single out too-many-requests
  src/main/java/org/commcare/formplayer/application/FormController.java
  src/main/java/org/commcare/formplayer/services/SubmitService.java
  src/main/java/org/commcare/formplayer/util/Constants.java
Labels: product/all-users
