Repository dimagi/formplayer, pull requests merged in 2021-01, with the labels that each got.

#801 Case claim default Value Support
  src/main/java/org/commcare/formplayer/beans/menus/DisplayElement.java
  src/main/java/org/commcare/formplayer/beans/menus/QueryResponseBean.java
  src/test/java/org/commcare/formplayer/tests/CaseClaimTests.java
  src/test/resources/archives/caseclaim.ccz
  src/test/resources/restores/caseclaim.xml
Labels: product/invisible

#806 Small changes to allow forcing user DB sync from HQ
  src/main/java/org/commcare/formplayer/application/UtilController.java
  src/main/java/org/commcare/formplayer/services/RestoreFactory.java
Labels: product/invisible

#807 check for existing advisory locks before running flyway migrations
  src/main/java/org/commcare/formplayer/db/callbacks/LockLoggingCallback.java
  src/main/resources/application.properties
Labels: product/invisible

#805 url encode loginas
  src/main/java/org/commcare/formplayer/services/RestoreFactory.java
Labels: product/all-users

#809 Revert "check for existing advisory locks before running flyway migrations"
  src/main/java/org/commcare/formplayer/db/callbacks/LockLoggingCallback.java
  src/main/resources/application.properties
Labels: product/invisible

#804 add flag for skipping full validation
  src/main/java/org/commcare/formplayer/api/json/JsonActionUtils.java
  src/main/java/org/commcare/formplayer/application/FormController.java
  src/main/java/org/commcare/formplayer/session/FormSession.java
Labels: product/invisible

#808 pass requesting user from formplayer back to HQ
  src/main/java/org/commcare/formplayer/services/RestoreFactory.java
Labels: product/invisible

#789 Added function comments [ci skip]
  src/main/java/org/commcare/formplayer/session/MenuSession.java
Labels: product/feature-flag, product/invisible

#815 enable spring boot actuator with health checks, info and metrics
  build.gradle
  src/main/java/org/commcare/formplayer/application/WebAppContext.java
  src/main/resources/application.properties
Labels: product/invisible

#816 upgrade gradle + config & remove unused dependencies
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: Awaiting QA, product/invisible

#818 use external tool for rebuildstaging workflow
  scripts/commit-staging
  scripts/gitutils.py
  scripts/rebuildstaging
  scripts/rebuildstaging-requirements.txt
  scripts/rebuildstaging.py
  scripts/sh_verbose.py
  scripts/staging.md
Labels: product/invisible

#817 add labels config
  .github/labels.yml
Labels: product/invisible

#819 remove swagger UI along with dependent config
  README.md
  build.gradle
  src/main/java/org/commcare/formplayer/application/DebuggerController.java
  src/main/java/org/commcare/formplayer/application/FormController.java
  src/main/java/org/commcare/formplayer/application/IncompleteSessionController.java
  src/main/java/org/commcare/formplayer/application/MenuController.java
  src/main/java/org/commcare/formplayer/application/SwaggerConfig.java
  src/main/java/org/commcare/formplayer/application/UtilController.java
  src/main/java/org/commcare/formplayer/application/WebAppContext.java
  src/main/java/org/commcare/formplayer/beans/AnswerQuestionRequestBean.java
  src/main/java/org/commcare/formplayer/beans/GetInstanceResponseBean.java
  src/main/java/org/commcare/formplayer/beans/JumpToIndexRequestBean.java
  src/main/java/org/commcare/formplayer/beans/SessionRequestBean.java
  src/main/java/org/commcare/formplayer/beans/SessionResponseBean.java
  src/main/java/org/commcare/formplayer/beans/menus/Command.java
  src/main/java/org/commcare/formplayer/beans/menus/EntityListResponse.java
  src/main/java/org/commcare/formplayer/util/Constants.java
Labels: product/invisible

#799 Case claim Itemset Support
  src/main/java/org/commcare/formplayer/application/MenuController.java
  src/main/java/org/commcare/formplayer/beans/SessionNavigationBean.java
  src/main/java/org/commcare/formplayer/beans/menus/DisplayElement.java
  src/main/java/org/commcare/formplayer/beans/menus/QueryResponseBean.java
  src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
  src/test/java/org/commcare/formplayer/tests/BaseTestClass.java
  src/test/java/org/commcare/formplayer/tests/CaseClaimTests.java
  src/test/resources/archives/caseclaim.ccz
Labels: product/feature-flag

#825 Add form name tag to sentry when creating form session
  src/main/java/org/commcare/formplayer/application/DebuggerController.java
  src/main/java/org/commcare/formplayer/application/FormController.java
  src/main/java/org/commcare/formplayer/services/NewFormResponseFactory.java
  src/main/java/org/commcare/formplayer/session/FormSession.java
  src/main/java/org/commcare/formplayer/util/FormplayerSentry.java
Labels: product/invisible
