Repository dimagi/formplayer, pull requests merged in 2021-03, with the labels that each got.

#906 custom JPA repository implementation to avoid 'select on update'
  src/main/java/org/commcare/formplayer/Application.java
  src/main/java/org/commcare/formplayer/repo/FormplayerBaseJpaRepoImpl.java
Labels: product/invisible

#907 Add form_name tag to navigate_menu requests that open forms
  src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
Labels: product/invisible

#874 Add module_name tag
  src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
  src/main/java/org/commcare/formplayer/util/Constants.java
Labels: product/invisible

#910 formplayer docker build
  .travis.yml
  scripts/docker_deploy.sh
Labels: product/invisible

#915 use restTemplate to download ccz
  src/main/java/org/commcare/formplayer/engine/FormplayerConfigEngine.java
  src/main/java/org/commcare/formplayer/services/InstallService.java
Labels: product/invisible

#918 enable code coverage
  .travis.yml
  build.gradle
Labels: product/invisible

#882 Take case list page size from Web Apps
  src/main/java/org/commcare/formplayer/application/MenuController.java
  src/main/java/org/commcare/formplayer/beans/SessionNavigationBean.java
  src/main/java/org/commcare/formplayer/beans/menus/EntityListResponse.java
  src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
  src/test/java/org/commcare/formplayer/tests/CasePaginationTests.java
  src/test/resources/requests/get_details/pagination_navigator_details.json
  src/test/resources/requests/navigators/pagination_navigator.json
  src/test/resources/requests/navigators/pagination_navigator_1.json
  src/test/resources/requests/navigators/search_paginate_navigator.json
Labels: QA Passed, open for review, product/all-users

#921 separate autosearch from skip default
  src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
Labels: product/feature-flag

#914 rest template cleanup
  src/main/java/org/commcare/formplayer/application/AbstractBaseController.java
  src/main/java/org/commcare/formplayer/application/FormController.java
  src/main/java/org/commcare/formplayer/application/MenuController.java
  src/main/java/org/commcare/formplayer/application/WebAppContext.java
  src/main/java/org/commcare/formplayer/screens/FormplayerQueryScreen.java
  src/main/java/org/commcare/formplayer/screens/FormplayerSyncScreen.java
  src/main/java/org/commcare/formplayer/services/FormattedQuestionsService.java
  src/main/java/org/commcare/formplayer/services/FormplayerFormSendCalloutHandler.java
  src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
  src/main/java/org/commcare/formplayer/services/NewFormResponseFactory.java
  src/main/java/org/commcare/formplayer/services/QueryRequester.java
  src/main/java/org/commcare/formplayer/services/RestoreFactory.java
  src/main/java/org/commcare/formplayer/services/SubmitService.java
  src/main/java/org/commcare/formplayer/services/SyncRequester.java
  src/main/java/org/commcare/formplayer/services/XFormService.java
  src/main/java/org/commcare/formplayer/web/client/RestTemplateConfig.java
  src/main/java/org/commcare/formplayer/web/client/WebClient.java
  src/test/java/org/commcare/formplayer/tests/BaseTestClass.java
  src/test/java/org/commcare/formplayer/tests/CaseClaimNavigationTests.java
  src/test/java/org/commcare/formplayer/tests/CaseClaimTests.java
  src/test/java/org/commcare/formplayer/tests/SubmitServiceTests.java
  src/test/java/org/commcare/formplayer/tests/SubmitTests.java
  src/test/java/org/commcare/formplayer/utils/TestContext.java
Labels: QA Passed, product/invisible

#908 add translations attr in form response
  src/main/java/org/commcare/formplayer/beans/menus/BaseResponseBean.java
  src/main/java/org/commcare/formplayer/services/NewFormResponseFactory.java
Labels: product/all-users-all-environments

#924 health check for connectivity to CommCare HQ
  src/main/java/org/commcare/formplayer/health/CommCareHealthCheck.java
Labels: product/invisible

#919 finalize form session cleanup
  src/main/java/org/commcare/formplayer/application/FormController.java
  src/main/java/org/commcare/formplayer/beans/SessionListItem.java
  src/main/java/org/commcare/formplayer/db/migration/V20__drop_deprecated_form_session_fields.java
  src/main/java/org/commcare/formplayer/objects/FormSessionListView.java
  src/main/java/org/commcare/formplayer/objects/FormSessionListViewRaw.java
  src/main/java/org/commcare/formplayer/objects/IntStringConverter.java
  src/main/java/org/commcare/formplayer/objects/SerializableFormSession.java
  src/main/java/org/commcare/formplayer/repo/FormSessionRepo.java
  src/main/java/org/commcare/formplayer/services/FormSessionService.java
  src/main/java/org/commcare/formplayer/services/NewFormResponseFactory.java
  src/main/java/org/commcare/formplayer/session/FormSession.java
  src/main/java/org/commcare/formplayer/util/Constants.java
  src/test/java/org/commcare/formplayer/repo/FormSessionRepoTest.java
  src/test/java/org/commcare/formplayer/services/FormSessionServiceTest.java
Labels: product/invisible

#920 formplayer locale installer to always save locale data in the application DB
  src/main/java/org/commcare/formplayer/installers/FormplayerInstallerFactory.java
  src/main/java/org/commcare/formplayer/installers/FormplayerLocaleInstaller.java
  src/main/java/org/commcare/formplayer/installers/SimpleInstaller.java
  src/main/java/org/commcare/formplayer/util/PrototypeUtils.java
Labels: product/invisible

#925 Note in README about local dev and docker
  README.md
Labels: product/invisible

#928 remove custom error handling
  src/main/java/org/commcare/formplayer/application/WebAppContext.java
Labels: product/invisible

#927 use builder instead of deprecated constructor
  src/main/java/org/commcare/formplayer/application/WebAppContext.java
Labels: product/invisible

#926 only log our views
  src/main/java/org/commcare/formplayer/Application.java
  src/main/java/org/commcare/formplayer/aspects/LoggingAspect.java
Labels: product/invisible

#932 Bug Fix: Search prompts getting skipped from case search
  src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
  src/test/java/org/commcare/formplayer/tests/CaseClaimTests.java
Labels: product/feature-flag

#935 apply getter at class level
  src/main/java/org/commcare/formplayer/objects/SerializableFormSession.java
Labels: product/invisible

#933 remove SqlHelper.SQL_DEBUG
  src/main/java/org/commcare/formplayer/database/models/FormplayerCaseIndexTable.java
  src/main/java/org/commcare/formplayer/engine/FormplayerCaseInstanceTreeElement.java
  src/main/java/org/commcare/formplayer/sandbox/SqlHelper.java
Labels: product/invisible

#936 AutoLaunch cleanup
  src/main/java/org/commcare/formplayer/session/MenuSession.java
Labels: product/invisible

#931 implement spring security filters for auth
  DEV_GUIDE.md
  build.gradle
  src/main/java/org/commcare/formplayer/application/AbstractBaseController.java
  src/main/java/org/commcare/formplayer/application/FormplayerAuthFilter.java
  src/main/java/org/commcare/formplayer/application/FormplayerSentryFilter.java
  src/main/java/org/commcare/formplayer/application/RequestResponseLoggingFilter.java
  src/main/java/org/commcare/formplayer/aspects/LockAspect.java
  src/main/java/org/commcare/formplayer/aspects/MetricsAspect.java
  src/main/java/org/commcare/formplayer/auth/CommCareSessionAuthFilter.java
  src/main/java/org/commcare/formplayer/auth/HmacAuthFilter.java
  src/main/java/org/commcare/formplayer/auth/UserDomainPreAuthPrincipal.java
  src/main/java/org/commcare/formplayer/beans/auth/HqUserDetailsBean.java
  src/main/java/org/commcare/formplayer/configuration/CorsConfig.java
  src/main/java/org/commcare/formplayer/configuration/StaticView.java
  src/main/java/org/commcare/formplayer/configuration/WebSecurityConfig.java
  src/main/java/org/commcare/formplayer/filters/FilterOrder.java
  src/main/java/org/commcare/formplayer/request/MultipleReadRequestWrappingFilter.java
  src/main/java/org/commcare/formplayer/services/CategoryTimingHelper.java
  src/main/java/org/commcare/formplayer/services/HqUserDetailsService.java
  src/main/java/org/commcare/formplayer/services/RestoreFactory.java
  src/main/java/org/commcare/formplayer/util/Constants.java
  src/main/java/org/commcare/formplayer/util/FormplayerHttpRequest.java
  src/main/java/org/commcare/formplayer/util/FormplayerSentryUserProvider.java
  src/main/java/org/commcare/formplayer/util/RequestUtils.java
  src/main/resources/application.properties
  src/test/java/org/commcare/formplayer/tests/HqUserDetailsTests.java
  src/test/java/org/commcare/formplayer/utils/TestContext.java
  src/test/java/org/commcare/formplayer/utils/WithHqUser.java
  src/test/java/org/commcare/formplayer/utils/WithHqUserSecurityContextFactory.java
  src/test/java/tests/RequestResponseLoggingFilterTest.java
Labels: QA Passed, product/invisible

#897 Adds a wrapper around connection handler for dual writing to sqlite and postgres
  build.gradle
  src/main/java/org/commcare/formplayer/postgresutil/PostgresApplicationDB.java
  src/main/java/org/commcare/formplayer/postgresutil/PostgresDB.java
  src/main/java/org/commcare/formplayer/postgresutil/PostgresProperties.java
  src/main/java/org/commcare/formplayer/postgresutil/PostgresSqlHelper.java
  src/main/java/org/commcare/formplayer/sandbox/SqlHelper.java
  src/main/java/org/commcare/formplayer/sandbox/SqlStorageWrapper.java
  src/main/java/org/commcare/formplayer/services/FormplayerStorageFactory.java
  src/main/java/org/commcare/formplayer/sqlitedb/SQLiteDB.java
Labels: don't pull, product/custom

#943 don't run session auth filter unless the cookie exists
  src/main/java/org/commcare/formplayer/auth/CommCareSessionAuthFilter.java
Labels: product/invisible

#944 add basic timing to answerQuestion
  src/main/java/org/commcare/formplayer/application/FormController.java
  src/main/java/org/commcare/formplayer/services/CategoryTimingHelper.java
  src/main/java/org/commcare/formplayer/util/Constants.java
  src/main/java/org/commcare/formplayer/util/FormplayerSentry.java
  src/main/java/org/commcare/formplayer/utils/CheckedSupplier.java
Labels: product/invisible

#934 remove default logging config
  .travis/application.example.properties
  config/application.docker.properties
  src/main/resources/application.properties
Labels: product/invisible

#946 disable system metrics
  src/main/resources/application.properties
Labels: product/invisible

#945 prune formplayer metrics to reduce cost + remove unused
  src/main/java/org/commcare/formplayer/aspects/MetricsAspect.java
  src/main/java/org/commcare/formplayer/util/Constants.java
  src/test/java/org/commcare/formplayer/tests/FormplayerDatadogTests.java
Labels: product/invisible
