Repository dimagi/formplayer, pull requests merged in 2021-05, with the labels that each got.

#956 remove unused 'additional_filters'
  src/main/java/org/commcare/formplayer/objects/SessionData.java
  src/test/resources/old_incomplete_session.json
  src/test/resources/requests/filter/filter_cases_4.json
  src/test/resources/requests/new_form/edit_form.json
  src/test/resources/requests/new_form/edit_image.json
  src/test/resources/requests/new_form/edit_user_data.json
  src/test/resources/requests/new_form/new_form.json
  src/test/resources/requests/new_form/new_form_2.json
  src/test/resources/requests/new_form/new_form_3.json
  src/test/resources/requests/new_form/new_form_4.json
  src/test/resources/requests/new_form/new_form_group.json
  src/test/resources/requests/new_form/new_form_oqps.json
Labels: product/invisible

#960 Auto advance Menu screen with single option
  src/main/java/org/commcare/formplayer/services/MenuSessionFactory.java
  src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
  src/main/java/org/commcare/formplayer/session/MenuSession.java
  src/main/java/org/commcare/formplayer/util/FormplayerPropertyManager.java
Labels: awaiting QA, open for review, product/custom

#958 Skips Auto launch Action for case search based on Xpath condition
  src/main/java/org/commcare/formplayer/beans/menus/EntityListResponse.java
  src/main/java/org/commcare/formplayer/services/MenuSessionFactory.java
  src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
  src/main/java/org/commcare/formplayer/session/MenuSession.java
  src/main/java/org/commcare/formplayer/util/FormplayerPropertyManager.java
  src/test/java/org/commcare/formplayer/tests/BaseTestClass.java
  src/test/java/org/commcare/formplayer/tests/BasicEndOfFormTests.java
  src/test/java/org/commcare/formplayer/tests/CaseClaimNavigationTests.java
  src/test/resources/archives/case_claim_eof_navigation.ccz
  src/test/resources/archives/case_claim_spf_other.ccz
  src/test/resources/archives/case_claim_spf_parent.ccz
Labels: awaiting QA, open for review, product/custom

#963 pass down templateforms list in getDetails for markdown
  src/main/java/org/commcare/formplayer/beans/menus/EntityDetailListResponse.java
  src/main/java/org/commcare/formplayer/beans/menus/EntityDetailResponse.java
Labels: product/all-users

#964 Feature flag checker for Formplayer, Kotlin Support
  build.gradle
  src/main/java/org/commcare/formplayer/auth/HmacAuthFilter.java
  src/main/java/org/commcare/formplayer/beans/auth/FeatureFlagChecker.kt
  src/main/java/org/commcare/formplayer/beans/auth/HqUserDetailsBean.java
  src/test/java/org/commcare/formplayer/tests/HqUserDetailsTests.java
  src/test/java/org/commcare/formplayer/utils/WithHqUser.java
  src/test/java/org/commcare/formplayer/utils/WithHqUserSecurityContextFactory.java
Labels: cross requested, product/invisible

#957 Fix and Revert "Revert "Manage MenuSession via Spring Jpa""
  src/main/java/org/commcare/formplayer/application/AbstractBaseController.java
  src/main/java/org/commcare/formplayer/application/DebuggerController.java
  src/main/java/org/commcare/formplayer/application/FormController.java
  src/main/java/org/commcare/formplayer/application/WebAppContext.java
  src/main/java/org/commcare/formplayer/objects/SerializableMenuSession.java
  src/main/java/org/commcare/formplayer/repo/MenuSessionRepo.java
  src/main/java/org/commcare/formplayer/repo/SerializableMenuSession.java
  src/main/java/org/commcare/formplayer/repo/impl/PostgresMenuSessionRepo.java
  src/main/java/org/commcare/formplayer/services/MenuSessionFactory.java
  src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
  src/main/java/org/commcare/formplayer/services/MenuSessionService.java
  src/main/java/org/commcare/formplayer/session/MenuSession.java
  src/main/java/org/commcare/formplayer/util/serializer/SessionSerializer.java
  src/main/resources/application.properties
  src/test/java/org/commcare/formplayer/mocks/MockMenuSessionRepo.java
  src/test/java/org/commcare/formplayer/repo/MenuSessionRepoTest.java
  src/test/java/org/commcare/formplayer/repo/impl/PostgresFormSessionRepoTest.java
  src/test/java/org/commcare/formplayer/tests/BaseTestClass.java
  src/test/java/org/commcare/formplayer/tests/HqUserDetailsServiceTests.java
  src/test/java/org/commcare/formplayer/utils/TestContext.java
Labels: product/invisible

#968 Remove claim success message
  src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
Labels: product/feature-flag
