Repository dimagi/formplayer, pull requests merged in 2021-04, with the labels that each got.

#949 record DD metrics for answer timings
  src/main/java/org/commcare/formplayer/application/FormController.java
  src/main/java/org/commcare/formplayer/services/CategoryTimingHelper.java
  src/main/java/org/commcare/formplayer/util/FormplayerSentry.java
Labels: product/invisible

#911 In Memory Cache For Case Search
  build.gradle
  src/main/java/org/commcare/formplayer/application/MenuController.java
  src/main/java/org/commcare/formplayer/application/WebAppContext.java
  src/main/java/org/commcare/formplayer/services/CaseSearchHelper.java
  src/main/java/org/commcare/formplayer/services/FormplayerFormSendCalloutHandler.java
  src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
  src/main/java/org/commcare/formplayer/services/RestoreFactory.java
  src/main/java/org/commcare/formplayer/util/SerializationUtil.java
  src/main/resources/application.properties
  src/test/java/org/commcare/formplayer/tests/BaseTestClass.java
  src/test/java/org/commcare/formplayer/tests/CaseClaimTests.java
  src/test/java/org/commcare/formplayer/utils/TestContext.java
Labels: product/custom

#929 Manage MenuSession via Spring Jpa
  src/main/java/org/commcare/formplayer/application/AbstractBaseController.java
  src/main/java/org/commcare/formplayer/application/DebuggerController.java
  src/main/java/org/commcare/formplayer/application/FormController.java
  src/main/java/org/commcare/formplayer/application/WebAppContext.java
  src/main/java/org/commcare/formplayer/objects/SerializableMenuSession.java
  src/main/java/org/commcare/formplayer/repo/MenuSessionRepo.java
  src/main/java/org/commcare/formplayer/repo/SerializableMenuSession.java
  src/main/java/org/commcare/formplayer/repo/impl/PostgresMenuSessionRepo.java
  src/main/java/org/commcare/formplayer/services/MenuSessionFactory.java
  src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
  src/main/java/org/commcare/formplayer/services/MenuSessionService.java
  src/main/java/org/commcare/formplayer/session/MenuSession.java
  src/main/java/org/commcare/formplayer/util/serializer/SessionSerializer.java
  src/test/java/org/commcare/formplayer/mocks/MockMenuSessionRepo.java
  src/test/java/org/commcare/formplayer/repo/MenuSessionRepoTest.java
  src/test/java/org/commcare/formplayer/repo/impl/PostgresFormSessionRepoTest.java
  src/test/java/org/commcare/formplayer/tests/BaseTestClass.java
  src/test/java/org/commcare/formplayer/tests/HqUserDetailsServiceTests.java
  src/test/java/org/commcare/formplayer/utils/TestContext.java
Labels: QA Passed, product/invisible

#930 Incomplete forms pagination support
  src/main/java/org/commcare/formplayer/application/IncompleteSessionController.java
  src/main/java/org/commcare/formplayer/beans/FormsSessionsRequestBean.java
  src/main/java/org/commcare/formplayer/beans/GetSessionsResponse.java
  src/main/java/org/commcare/formplayer/repo/FormSessionRepo.java
  src/main/java/org/commcare/formplayer/services/FormSessionService.java
  src/test/java/org/commcare/formplayer/repo/FormSessionRepoTest.java
  src/test/java/org/commcare/formplayer/services/FormSessionServiceTest.java
  src/test/java/org/commcare/formplayer/services/FormSessionsPaginationTest.java
Labels: QA Passed, product/invisible

#954 Revert "Manage MenuSession via Spring Jpa"
  src/main/java/org/commcare/formplayer/application/AbstractBaseController.java
  src/main/java/org/commcare/formplayer/application/DebuggerController.java
  src/main/java/org/commcare/formplayer/application/FormController.java
  src/main/java/org/commcare/formplayer/application/WebAppContext.java
  src/main/java/org/commcare/formplayer/objects/SerializableMenuSession.java
  src/main/java/org/commcare/formplayer/repo/MenuSessionRepo.java
  src/main/java/org/commcare/formplayer/repo/SerializableMenuSession.java
  src/main/java/org/commcare/formplayer/repo/impl/PostgresMenuSessionRepo.java
  src/main/java/org/commcare/formplayer/services/MenuSessionFactory.java
  src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
  src/main/java/org/commcare/formplayer/services/MenuSessionService.java
  src/main/java/org/commcare/formplayer/session/MenuSession.java
  src/main/java/org/commcare/formplayer/util/serializer/SessionSerializer.java
  src/test/java/org/commcare/formplayer/mocks/MockMenuSessionRepo.java
  src/test/java/org/commcare/formplayer/repo/MenuSessionRepoTest.java
  src/test/java/org/commcare/formplayer/repo/impl/PostgresFormSessionRepoTest.java
  src/test/java/org/commcare/formplayer/tests/BaseTestClass.java
  src/test/java/org/commcare/formplayer/tests/HqUserDetailsServiceTests.java
  src/test/java/org/commcare/formplayer/utils/TestContext.java
Labels: product/invisible

#955 enable caching by default
  src/main/resources/application.properties
Labels: product/invisible

#898 only scan references until found
  src/main/java/org/commcare/formplayer/services/MenuSessionFactory.java
Labels: product/invisible
