Repository dimagi/formplayer, pull requests merged in 2021-02, with the labels that each got.

#835 Increase default lock pool size from 255 to 65k
  src/main/java/org/commcare/formplayer/services/FormplayerLockRegistry.java
Labels: product/all-users-all-environments

#829 Bump jsonpath version
  build.gradle
Labels: dependencies, product/invisible

#839 use exists instead of count
  src/main/java/org/commcare/formplayer/repo/impl/PostgresFormSessionRepo.java
Labels: product/invisible

#833 Add form_name tag to datadog metrics for submit-all requests
  src/main/java/org/commcare/formplayer/aspects/MetricsAspect.java
Labels: product/invisible

#811 Revert "Revert "url encode loginas""
  src/main/java/org/commcare/formplayer/services/RestoreFactory.java
Labels: QA Passed, product/all-users

#836 tests for validation on submit
  build.gradle
  src/main/java/org/commcare/formplayer/beans/menus/ErrorBean.java
  src/test/java/org/commcare/formplayer/tests/BaseTestClass.java
  src/test/java/org/commcare/formplayer/tests/FormEntryTest.java
  src/test/resources/xforms/constraints.xml
  src/test/resources/xforms/constraints_minimal.xml
Labels: product/invisible

#832 Send form name to datadog for granular timings on submit requests
  src/main/java/org/commcare/formplayer/application/FormController.java
  src/main/java/org/commcare/formplayer/services/CategoryTimingHelper.java
  src/main/java/org/commcare/formplayer/services/RestoreFactory.java
Labels: product/invisible

#838 Add slow request thresholds for specific requests
  src/main/java/org/commcare/formplayer/aspects/MetricsAspect.java
Labels: product/invisible

#842 Move adding tag to FormController
  src/main/java/org/commcare/formplayer/application/DebuggerController.java
  src/main/java/org/commcare/formplayer/application/FormController.java
  src/main/java/org/commcare/formplayer/services/NewFormResponseFactory.java
  src/main/java/org/commcare/formplayer/session/FormSession.java
Labels: product/invisible

#841 Sk/cache form session
  build.gradle
  src/main/java/org/commcare/formplayer/Application.java
  src/main/java/org/commcare/formplayer/objects/SerializableFormSession.java
  src/main/java/org/commcare/formplayer/repo/impl/PostgresFormSessionRepo.java
  src/main/resources/application.properties
  src/test/java/org/commcare/formplayer/repo/impl/PostgresFormSessionRepoTest.java
  src/test/java/org/commcare/formplayer/tests/BaseTestClass.java
  src/test/java/org/commcare/formplayer/tests/FormValidatorTests.java
Labels: product/invisible

#845 reuse 'as' parameter when doing a force sync
  src/main/java/org/commcare/formplayer/services/RestoreFactory.java
Labels: product/invisible

#847 add spring boot devtools
  build.gradle
Labels: product/invisible

#812 skip json creation on validation
  src/main/java/org/commcare/formplayer/api/json/JsonActionUtils.java
  src/main/java/org/commcare/formplayer/application/FormController.java
  src/main/java/org/commcare/formplayer/session/FormSession.java
Labels: product/invisible

#848 use junit5
  build.gradle
  src/main/java/org/commcare/formplayer/application/WebAppContext.java
  src/main/java/org/commcare/formplayer/services/RestoreFactory.java
  src/main/java/org/commcare/formplayer/util/FormplayerSentry.java
  src/main/java/org/commcare/formplayer/util/RequestUtils.java
  src/test/java/org/commcare/formplayer/repo/impl/PostgresFormSessionRepoTest.java
  src/test/java/org/commcare/formplayer/tests/ApplicationUtilsTests.java
  src/test/java/org/commcare/formplayer/tests/AsyncRestoreTest.java
  src/test/java/org/commcare/formplayer/tests/BaseTestClass.java
  src/test/java/org/commcare/formplayer/tests/BasicEndOfFormTests.java
  src/test/java/org/commcare/formplayer/tests/BrowserValuesProviderTest.java
  src/test/java/org/commcare/formplayer/tests/CaseClaimTests.java
  src/test/java/org/commcare/formplayer/tests/CaseDbIndexTests.java
  src/test/java/org/commcare/formplayer/tests/CaseDbModelQueryTests.java
  src/test/java/org/commcare/formplayer/tests/CaseDbOptimizationsTest.java
  src/test/java/org/commcare/formplayer/tests/CaseDbQueryTest.java
  src/test/java/org/commcare/formplayer/tests/CasePaginationTests.java
  src/test/java/org/commcare/formplayer/tests/CaseTests.java
  src/test/java/org/commcare/formplayer/tests/CaseTilesTest.java
  src/test/java/org/commcare/formplayer/tests/DeleteApplicationDbsTests.java
  src/test/java/org/commcare/formplayer/tests/DetailNodesetTest.java
  src/test/java/org/commcare/formplayer/tests/DoubleManagementTest.java
  src/test/java/org/commcare/formplayer/tests/EditTest.java
  src/test/java/org/commcare/formplayer/tests/Enikshay2bTests.java
  src/test/java/org/commcare/formplayer/tests/EnikshayEndOfFormTests.java
  src/test/java/org/commcare/formplayer/tests/EnikshayTests.java
  src/test/java/org/commcare/formplayer/tests/FilterTests.java
  src/test/java/org/commcare/formplayer/tests/FormEntryTest.java
  src/test/java/org/commcare/formplayer/tests/FormValidatorTests.java
  src/test/java/org/commcare/formplayer/tests/FormplayerDateUtilsTest.java
  src/test/java/org/commcare/formplayer/tests/FormplayerRavenTest.java
  src/test/java/org/commcare/formplayer/tests/GeoTests.java
  src/test/java/org/commcare/formplayer/tests/GroupTests.java
  src/test/java/org/commcare/formplayer/tests/HqUserDetailsServiceTests.java
  src/test/java/org/commcare/formplayer/tests/HqUserDetailsTests.java
  src/test/java/org/commcare/formplayer/tests/IndexedFixtureTest.java
  src/test/java/org/commcare/formplayer/tests/InlineCaseTilesTest.java
  src/test/java/org/commcare/formplayer/tests/InstallTests.java
  src/test/java/org/commcare/formplayer/tests/JsonUtilTests.java
  src/test/java/org/commcare/formplayer/tests/LocalizationTests.java
  src/test/java/org/commcare/formplayer/tests/MenuDebuggerTests.java
  src/test/java/org/commcare/formplayer/tests/NewFormTests.java
  src/test/java/org/commcare/formplayer/tests/OQPSDateRegression.java
  src/test/java/org/commcare/formplayer/tests/ParentChildTest.java
  src/test/java/org/commcare/formplayer/tests/ReassignCaseTest.java
  src/test/java/org/commcare/formplayer/tests/RegressionTests.java
  src/test/java/org/commcare/formplayer/tests/RepeatTests.java
  src/test/java/org/commcare/formplayer/tests/RestoreFactoryTest.java
  src/test/java/org/commcare/formplayer/tests/SchedulerTest.java
  src/test/java/org/commcare/formplayer/tests/SmsFormEntryTest.java
  src/test/java/org/commcare/formplayer/tests/SnapshotTests.java
  src/test/java/org/commcare/formplayer/tests/SubmitServiceTests.java
  src/test/java/org/commcare/formplayer/tests/SubmitTests.java
  src/test/java/org/commcare/formplayer/tests/UserUtilsTests.java
  src/test/java/org/commcare/formplayer/tests/sandbox/CaseAPITests.java
  src/test/java/org/commcare/formplayer/tests/sandbox/SqlStorageIndexedTests.java
  src/test/java/org/commcare/formplayer/tests/sandbox/UserSqlSandboxTest.java
  src/test/java/org/commcare/formplayer/utils/DbTestUtils.java
  src/test/java/org/commcare/formplayer/utils/GenerateSnapshotDatabases.java
  src/test/java/tests/RequestResponseLoggingFilterTest.java
Labels: product/invisible

#840 Datadog wrapper
  src/main/java/org/commcare/formplayer/application/WebAppContext.java
  src/main/java/org/commcare/formplayer/aspects/MetricsAspect.java
  src/main/java/org/commcare/formplayer/util/FormplayerDatadog.java
  src/test/java/org/commcare/formplayer/tests/BaseTestClass.java
  src/test/java/org/commcare/formplayer/tests/FormplayerDatadogTests.java
  src/test/java/org/commcare/formplayer/utils/TestContext.java
Labels: product/invisible

#851 Use datadog wrapper to add form_name tag
  src/main/java/org/commcare/formplayer/application/FormController.java
  src/main/java/org/commcare/formplayer/aspects/MetricsAspect.java
  src/main/java/org/commcare/formplayer/services/CategoryTimingHelper.java
  src/main/java/org/commcare/formplayer/services/RestoreFactory.java
  src/main/java/org/commcare/formplayer/util/Constants.java
  src/main/java/org/commcare/formplayer/util/FormplayerSentry.java
Labels: product/invisible

#846 form session service
  .travis/application.example.properties
  config/application.docker.properties
  config/application.example.properties
  src/main/java/org/commcare/formplayer/Application.java
  src/main/java/org/commcare/formplayer/application/AbstractBaseController.java
  src/main/java/org/commcare/formplayer/application/DebuggerController.java
  src/main/java/org/commcare/formplayer/application/FormController.java
  src/main/java/org/commcare/formplayer/application/FormplayerAuthFilter.java
  src/main/java/org/commcare/formplayer/application/IncompleteSessionController.java
  src/main/java/org/commcare/formplayer/application/UtilController.java
  src/main/java/org/commcare/formplayer/application/WebAppContext.java
  src/main/java/org/commcare/formplayer/aspects/LockAspect.java
  src/main/java/org/commcare/formplayer/aspects/MetricsAspect.java
  src/main/java/org/commcare/formplayer/aspects/UserRestoreAspect.java
  src/main/java/org/commcare/formplayer/objects/ByteArrayConverter.java
  src/main/java/org/commcare/formplayer/objects/FunctionHandler.java
  src/main/java/org/commcare/formplayer/objects/IntStringConverter.java
  src/main/java/org/commcare/formplayer/objects/SerializableFormSession.java
  src/main/java/org/commcare/formplayer/repo/FormSessionRepo.java
  src/main/java/org/commcare/formplayer/repo/impl/PostgresFormSessionRepo.java
  src/main/java/org/commcare/formplayer/services/FormSessionService.java
  src/main/java/org/commcare/formplayer/services/FormplayerStorageFactory.java
  src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
  src/main/java/org/commcare/formplayer/services/NewFormResponseFactory.java
  src/main/java/org/commcare/formplayer/services/ScheduledTasks.java
  src/main/java/org/commcare/formplayer/session/FormSession.java
  src/main/java/org/commcare/formplayer/util/FormplayerSentry.java
  src/main/resources/application.properties
  src/test/java/org/commcare/formplayer/mocks/MockFormSessionRepo.java
  src/test/java/org/commcare/formplayer/repo/FormSessionRepoTest.java
  src/test/java/org/commcare/formplayer/repo/impl/PostgresFormSessionRepoTest.java
  src/test/java/org/commcare/formplayer/services/FormSessionServiceTest.java
  src/test/java/org/commcare/formplayer/tests/BaseTestClass.java
  src/test/java/org/commcare/formplayer/tests/HqUserDetailsServiceTests.java
  src/test/java/org/commcare/formplayer/tests/LocalizationTests.java
  src/test/java/org/commcare/formplayer/tests/SubmitServiceTests.java
  src/test/java/org/commcare/formplayer/tests/SubmitTests.java
  src/test/java/org/commcare/formplayer/utils/JpaTestUtils.java
  src/test/java/org/commcare/formplayer/utils/TestContext.java
Labels: product/invisible

#856 use a better UUID generation strategy
  src/main/java/org/commcare/formplayer/objects/SerializableFormSession.java
Labels: product/invisible

#849 misc refactoring
  src/main/java/org/commcare/formplayer/application/DebuggerController.java
  src/main/java/org/commcare/formplayer/application/FormController.java
  src/main/java/org/commcare/formplayer/beans/InstanceXmlBean.java
  src/main/java/org/commcare/formplayer/beans/NewFormResponse.java
  src/main/java/org/commcare/formplayer/beans/NewSessionRequestBean.java
  src/main/java/org/commcare/formplayer/objects/SerializableFormSession.java
  src/main/java/org/commcare/formplayer/repo/SerializableMenuSession.java
  src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
  src/main/java/org/commcare/formplayer/services/NewFormResponseFactory.java
  src/main/java/org/commcare/formplayer/session/FormSession.java
  src/main/java/org/commcare/formplayer/session/MenuSession.java
  src/test/java/org/commcare/formplayer/repo/impl/PostgresFormSessionRepoTest.java
  src/test/java/org/commcare/formplayer/tests/CaseTests.java
Labels: product/invisible

#855 Add module tag
  src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
  src/main/java/org/commcare/formplayer/util/Constants.java
Labels: product/invisible

#860 more miscellaneous refactoring
  src/main/java/org/commcare/formplayer/session/FormSession.java
  src/main/java/org/commcare/formplayer/util/serializer/FormDefStringSerializer.java
Labels: product/invisible

#861 Use resolved install reference
  src/main/java/org/commcare/formplayer/session/MenuSession.java
Labels: product/invisible

#863 clean up request beans
  src/main/java/org/commcare/formplayer/annotations/AppInstall.java
  src/main/java/org/commcare/formplayer/annotations/ConfigureStorageFromSession.java
  src/main/java/org/commcare/formplayer/annotations/NoLogging.java
  src/main/java/org/commcare/formplayer/annotations/UserLock.java
  src/main/java/org/commcare/formplayer/annotations/UserRestore.java
  src/main/java/org/commcare/formplayer/application/IncompleteSessionController.java
  src/main/java/org/commcare/formplayer/application/MenuController.java
  src/main/java/org/commcare/formplayer/aspects/LockAspect.java
  src/main/java/org/commcare/formplayer/aspects/UserRestoreAspect.java
  src/main/java/org/commcare/formplayer/beans/AuthenticatedRequestBean.java
  src/main/java/org/commcare/formplayer/beans/CaseFilterRequestBean.java
  src/main/java/org/commcare/formplayer/beans/GetSessionsBean.java
  src/main/java/org/commcare/formplayer/beans/IncompleteSessionRequestBean.java
  src/main/java/org/commcare/formplayer/beans/InstallFromSessionRequestBean.java
  src/main/java/org/commcare/formplayer/beans/SessionRequestBean.java
  src/main/java/org/commcare/formplayer/beans/menus/UpdateRequestBean.java
  src/main/java/org/commcare/formplayer/session/MenuSession.java
  src/test/java/org/commcare/formplayer/beans/SessionRequestBeanTest.java
  src/test/java/org/commcare/formplayer/tests/BaseTestClass.java
Labels: product/invisible

#862 add column to form session table to replace incorrectly typed columns
  src/main/java/org/commcare/formplayer/configuration/JpaAuditConfiguration.java
  src/main/java/org/commcare/formplayer/db/migration/V19__form_session_correctly_typed_fields.java
  src/main/java/org/commcare/formplayer/objects/SerializableFormSession.java
  src/test/java/org/commcare/formplayer/repo/FormSessionRepoTest.java
Labels: product/invisible

#869 fix session list view for old sessions (with 'null' version)
  src/main/java/org/commcare/formplayer/objects/SerializableFormSession.java
  src/main/java/org/commcare/formplayer/repo/FormSessionRepo.java
  src/main/java/org/commcare/formplayer/services/FormSessionService.java
  src/test/java/org/commcare/formplayer/repo/FormSessionRepoTest.java
Labels: product/invisible

#865 remove the ability to pass install reference into formplayer
  build.gradle
  src/main/java/org/commcare/formplayer/application/AbstractBaseController.java
  src/main/java/org/commcare/formplayer/application/MenuController.java
  src/main/java/org/commcare/formplayer/aspects/AppInstallAspect.java
  src/main/java/org/commcare/formplayer/beans/InstallRequestBean.java
  src/main/java/org/commcare/formplayer/services/MenuSessionFactory.java
  src/main/java/org/commcare/formplayer/session/MenuSession.java
  src/main/java/org/commcare/formplayer/util/Constants.java
  src/main/java/org/commcare/formplayer/util/SessionUtils.java
  src/test/java/org/commcare/formplayer/tests/BaseTestClass.java
  src/test/java/org/commcare/formplayer/tests/DeleteApplicationDbsTests.java
  src/test/java/org/commcare/formplayer/utils/CheckedSupplier.java
  src/test/resources/requests/navigators/navigator_0.json
Labels: QA Passed, product/invisible

#868 form session projection for list view
  src/main/java/org/commcare/formplayer/application/IncompleteSessionController.java
  src/main/java/org/commcare/formplayer/beans/GetSessionsResponse.java
  src/main/java/org/commcare/formplayer/beans/SessionListItem.java
  src/main/java/org/commcare/formplayer/objects/FormSessionListView.java
  src/main/java/org/commcare/formplayer/objects/FormSessionListViewRaw.java
  src/main/java/org/commcare/formplayer/repo/FormSessionRepo.java
  src/main/java/org/commcare/formplayer/services/FormSessionService.java
  src/test/java/org/commcare/formplayer/repo/FormSessionRepoTest.java
  src/test/java/org/commcare/formplayer/services/FormSessionServiceTest.java
  src/test/java/org/commcare/formplayer/utils/JpaTestUtils.java
Labels: product/invisible

#867 only update changing fields when saving form sessions
  build.gradle
  src/main/java/org/commcare/formplayer/objects/SerializableFormSession.java
  src/main/java/org/commcare/formplayer/session/FormSession.java
  src/test/java/org/commcare/formplayer/repo/FormSessionRepoTest.java
  src/test/java/org/commcare/formplayer/services/FormSessionServiceTest.java
  src/test/java/org/commcare/formplayer/tests/BaseTestClass.java
Labels: product/invisible

#866 Refactor formplayer datadog wrapper to support detailed tagging
  config/application.example.properties
  src/main/java/org/commcare/formplayer/application/FormController.java
  src/main/java/org/commcare/formplayer/application/WebAppContext.java
  src/main/java/org/commcare/formplayer/aspects/MetricsAspect.java
  src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
  src/main/java/org/commcare/formplayer/util/FormplayerDatadog.java
  src/test/java/org/commcare/formplayer/tests/FormplayerDatadogTests.java
  src/test/java/org/commcare/formplayer/utils/TestContext.java
Labels: product/invisible

#871 Revert "Revert "only update changing fields when saving form sessions""
  build.gradle
  src/main/java/org/commcare/formplayer/objects/SerializableFormSession.java
  src/main/java/org/commcare/formplayer/session/FormSession.java
  src/test/java/org/commcare/formplayer/repo/FormSessionRepoTest.java
  src/test/java/org/commcare/formplayer/services/FormSessionServiceTest.java
  src/test/java/org/commcare/formplayer/tests/BaseTestClass.java
Labels: product/invisible

#873 limit form sessions returned by incomplete session view to those of the correct domain & login user
  src/main/java/org/commcare/formplayer/application/IncompleteSessionController.java
  src/main/java/org/commcare/formplayer/repo/FormSessionRepo.java
  src/main/java/org/commcare/formplayer/services/FormSessionService.java
  src/test/java/org/commcare/formplayer/repo/FormSessionRepoTest.java
  src/test/java/org/commcare/formplayer/services/FormSessionServiceTest.java
Labels: product/invisible

#883 fix repeat bug caused by side effects in `getFullFormJSON`
  src/main/java/org/commcare/formplayer/application/FormController.java
  src/main/java/org/commcare/formplayer/beans/NewFormResponse.java
  src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
  src/main/java/org/commcare/formplayer/services/NewFormResponseFactory.java
  src/main/java/org/commcare/formplayer/session/FormSession.java
  src/test/java/org/commcare/formplayer/tests/RepeatTests.java
  src/test/resources/xforms/repeat_model_iteration.xml
Labels: product/invisible

#881 populate version along with sequence ID
  .travis.yml
  src/main/java/org/commcare/formplayer/objects/SerializableFormSession.java
  src/test/java/org/commcare/formplayer/repo/FormSessionRepoTest.java
Labels: product/invisible

#891 add interrupt check at decompress
  src/main/java/org/commcare/formplayer/sandbox/ArchivableFile.java
Labels: product/all-users

#878 upgrade spring-boot and related dependencies
  .travis.yml
  build.gradle
  src/main/java/org/commcare/formplayer/application/WebAppContext.java
Labels: QA Passed, product/invisible

#884 Added URL encoding to case claim URL
  src/main/java/org/commcare/formplayer/screens/FormplayerSyncScreen.java
Labels: product/invisible

#886 upgrade sentry and refactor sentry usage
  .travis/application.example.properties
  build.gradle
  config/application.docker.properties
  config/application.example.properties
  sentry.properties
  src/main/java/org/commcare/formplayer/application/AbstractBaseController.java
  src/main/java/org/commcare/formplayer/application/DebuggerController.java
  src/main/java/org/commcare/formplayer/application/FormController.java
  src/main/java/org/commcare/formplayer/application/FormplayerAuthFilter.java
  src/main/java/org/commcare/formplayer/application/FormplayerSentryFilter.java
  src/main/java/org/commcare/formplayer/application/WebAppContext.java
  src/main/java/org/commcare/formplayer/aspects/AppInstallAspect.java
  src/main/java/org/commcare/formplayer/aspects/LockAspect.java
  src/main/java/org/commcare/formplayer/aspects/LoggingAspect.java
  src/main/java/org/commcare/formplayer/aspects/MetricsAspect.java
  src/main/java/org/commcare/formplayer/aspects/UserRestoreAspect.java
  src/main/java/org/commcare/formplayer/beans/EvaluateXPathResponseBean.java
  src/main/java/org/commcare/formplayer/services/BrowserValuesProvider.java
  src/main/java/org/commcare/formplayer/services/CategoryTimingHelper.java
  src/main/java/org/commcare/formplayer/services/FallbackSentryReporter.java
  src/main/java/org/commcare/formplayer/services/FormSessionService.java
  src/main/java/org/commcare/formplayer/services/FormplayerLockRegistry.java
  src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
  src/main/java/org/commcare/formplayer/services/RestoreFactory.java
  src/main/java/org/commcare/formplayer/util/Constants.java
  src/main/java/org/commcare/formplayer/util/FormplayerSentry.java
  src/main/java/org/commcare/formplayer/util/FormplayerSentryUserProvider.java
  src/main/java/org/commcare/formplayer/util/RequestUtils.java
  src/main/resources/application.properties
  src/test/java/org/commcare/formplayer/tests/BaseTestClass.java
  src/test/java/org/commcare/formplayer/tests/FormplayerRavenTest.java
  src/test/java/org/commcare/formplayer/utils/TestContext.java
Labels: product/invisible

#900 Case claim tests
  src/test/java/org/commcare/formplayer/tests/BaseTestClass.java
  src/test/java/org/commcare/formplayer/tests/CaseClaimNavigationTests.java
  src/test/resources/archives/case_claim_spf_other.ccz
  src/test/resources/archives/case_claim_spf_parent.ccz
  src/test/resources/query_responses/case_claim_parent_child_child_response.xml
  src/test/resources/query_responses/case_claim_parent_child_response.xml
  src/test/resources/restores/case_claim_parent_child.xml
Labels: product/invisible
