Repository dimagi/formplayer, pull requests merged in 2021-08, with the labels that each got.

#988 Validates additional answers when answering a question
  src/main/java/org/commcare/formplayer/application/FormController.java
  src/main/java/org/commcare/formplayer/beans/AnswerQuestionRequestBean.java
  src/main/java/org/commcare/formplayer/beans/FormEntryResponseBean.java
  src/main/java/org/commcare/formplayer/util/Constants.java
Labels: product/all-users, QA Passed

#993 Updated endpoint args exception handling
  src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
Labels: product/invisible

#995 Revert "Validates additional answers when answering a question"
  src/main/java/org/commcare/formplayer/application/FormController.java
  src/main/java/org/commcare/formplayer/beans/AnswerQuestionRequestBean.java
  src/main/java/org/commcare/formplayer/beans/FormEntryResponseBean.java
  src/main/java/org/commcare/formplayer/util/Constants.java
Labels: product/all-users-all-environments

#997 Revert "Revert "Validates additional answers when answering a question""
  src/main/java/org/commcare/formplayer/application/FormController.java
  src/main/java/org/commcare/formplayer/beans/AnswerQuestionRequestBean.java
  src/main/java/org/commcare/formplayer/beans/FormEntryResponseBean.java
  src/main/java/org/commcare/formplayer/util/Constants.java
Labels: product/invisible

#992 Smart linking MVP: claim cases on formplayer
  src/main/java/org/commcare/formplayer/screens/FormplayerSyncScreen.java
  src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
Labels: product/invisible

#998 Update c3 and d3
  src/main/java/org/commcare/formplayer/util/FormplayerGraphUtil.java
Labels: product/feature-flag

#1001 Added logic for setting menu session data to startFormEntry
  src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
Labels: product/invisible
