Repository dimagi/formplayer, pull requests merged in 2022-05, with the labels that each got.

#1135 Added breadcrumb support for MultiSelectEntityScreen
  src/main/java/org/commcare/formplayer/session/MenuSession.java
Labels: product/feature-flag, cross requested

#1139 Refactors VirtualDataInstance to extend from ExternalDataInstance
  src/main/java/org/commcare/formplayer/application/AbstractBaseController.java
  src/main/java/org/commcare/formplayer/db/migration/V23__init_virtual_data_instance.java
  src/main/java/org/commcare/formplayer/exceptions/InstanceNotFoundException.java
  src/main/java/org/commcare/formplayer/objects/SerializableDataInstance.java
  src/main/java/org/commcare/formplayer/repo/VirtualDataInstanceRepo.java
  src/main/java/org/commcare/formplayer/services/CaseSearchHelper.java
  src/main/java/org/commcare/formplayer/services/FormplayerRemoteInstanceFetcher.java
  src/main/java/org/commcare/formplayer/services/MenuSessionFactory.java
  src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
  src/main/java/org/commcare/formplayer/services/NewFormResponseFactory.java
  src/main/java/org/commcare/formplayer/services/VirtualDataInstanceService.java
  src/main/java/org/commcare/formplayer/session/FormSession.java
  src/main/java/org/commcare/formplayer/session/FormplayerInstanceInitializer.java
  src/main/java/org/commcare/formplayer/session/FormplayerSessionWrapper.java
  src/main/java/org/commcare/formplayer/session/MenuSession.java
  src/test/java/org/commcare/formplayer/repo/VirtualDataInstanceRepoTest.java
  src/test/java/org/commcare/formplayer/services/VirtualDataInstanceServiceTest.java
  src/test/java/org/commcare/formplayer/tests/BaseTestClass.java
  src/test/java/org/commcare/formplayer/tests/MultiSelectCaseClaimTest.java
  src/test/java/org/commcare/formplayer/tests/SavedFormDefTest.java
  src/test/java/org/commcare/formplayer/utils/TestStorageUtils.java
Labels: product/invisible

#1127 Cache deserialized FormDef by session id
  src/main/java/org/commcare/formplayer/application/AbstractBaseController.java
  src/main/java/org/commcare/formplayer/aspects/ConfigureStorageFromSessionAspect.java
  src/main/java/org/commcare/formplayer/objects/SerializableFormDefinition.java
  src/main/java/org/commcare/formplayer/services/FormDefinitionService.java
  src/main/java/org/commcare/formplayer/services/FormplayerStorageFactory.java
  src/main/java/org/commcare/formplayer/services/NewFormResponseFactory.java
  src/main/java/org/commcare/formplayer/session/FormSession.java
  src/test/java/org/commcare/formplayer/services/FormDefinitionServiceTest.java
  src/test/java/org/commcare/formplayer/tests/BaseTestClass.java
  src/test/java/org/commcare/formplayer/tests/SavedFormDefTest.java
  src/test/java/org/commcare/formplayer/utils/TestContext.java
Labels: product/invisible, QA Passed

#1146 use query data in debugger endpoints
  src/main/java/org/commcare/formplayer/application/DebuggerController.java
  src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
Labels: product/invisible

#1150 Revert "move addSelection to handleInput"
  src/main/java/org/commcare/formplayer/services/MenuSessionFactory.java
  src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
  src/main/java/org/commcare/formplayer/session/MenuSession.java
Labels: product/invisible
