Repository dimagi/formplayer, pull requests merged in 2022-03, with the labels that each got.

#1097 Fix for search again workflows
  src/main/java/org/commcare/formplayer/objects/QueryData.java
  src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
  src/test/java/org/commcare/formplayer/tests/BaseTestClass.java
  src/test/java/org/commcare/formplayer/tests/CaseClaimNavigationTests.java
  src/test/java/org/commcare/formplayer/tests/CaseClaimTests.java
  src/test/java/org/commcare/formplayer/tests/FormEntryWithQueryTests.java
  src/test/java/org/commcare/formplayer/tests/SmartLinkTests.java
  src/test/resources/archives/smart_link.ccz
  src/test/resources/query_responses/smart_link_default_response.xml
  src/test/resources/query_responses/smart_link_search_again_response.xml
Labels: product/custom

#1100 include queryKey in EntityList responses
  src/main/java/org/commcare/formplayer/beans/menus/CommandListResponseBean.java
  src/main/java/org/commcare/formplayer/beans/menus/EntityListResponse.java
  src/main/java/org/commcare/formplayer/beans/menus/MenuBean.java
  src/main/java/org/commcare/formplayer/beans/menus/QueryResponseBean.java
Labels: product/all-users-all-environments

#1102 Bump max line length to 115
  .ide_settings/codestyles/CommCare Coding Style.xml
  checkstyle.xml
Labels: product/invisible
