Repository dimagi/formplayer, pull requests merged in 2022-04, with the labels that each got.

#1119 Create form definition table in Postgres
  src/main/java/org/commcare/formplayer/db/migration/V22__create_form_definition.java
  src/main/java/org/commcare/formplayer/objects/SerializableFormDefinition.java
  src/main/java/org/commcare/formplayer/objects/SerializableFormSession.java
Labels: product/invisible

#1115 Tests for case claim with a multi select entity list
  src/test/java/org/commcare/formplayer/tests/BaseTestClass.java
  src/test/java/org/commcare/formplayer/tests/MultiSelectCaseClaimTest.java
  src/test/resources/archives/case_claim_with_multi_select/default/app_strings.txt
  src/test/resources/archives/case_claim_with_multi_select/media_suite.xml
  src/test/resources/archives/case_claim_with_multi_select/modules-0/forms-0.xml
  src/test/resources/archives/case_claim_with_multi_select/modules-1/forms-0.xml
  src/test/resources/archives/case_claim_with_multi_select/modules-1/forms-1.xml
  src/test/resources/archives/case_claim_with_multi_select/profile.ccpr
  src/test/resources/archives/case_claim_with_multi_select/suite.xml
  src/test/resources/query_responses/case_search_multi_select_response.xml
Labels: product/invisible

#1118 Switch Entities selection table to Postgress
  src/main/java/org/commcare/formplayer/application/AbstractBaseController.java
  src/main/java/org/commcare/formplayer/database/models/EntitiesSelectionStorage.java
  src/main/java/org/commcare/formplayer/db/migration/V23__init_entities_selection.java
  src/main/java/org/commcare/formplayer/objects/EntitiesSelection.java
  src/main/java/org/commcare/formplayer/repo/EntitiesSelectionRepo.java
  src/main/java/org/commcare/formplayer/services/EntitiesSelectionService.java
  src/main/java/org/commcare/formplayer/services/FormSessionService.java
  src/main/java/org/commcare/formplayer/services/MenuSessionFactory.java
  src/main/java/org/commcare/formplayer/services/NewFormResponseFactory.java
  src/main/java/org/commcare/formplayer/services/ScheduledTasks.java
  src/main/java/org/commcare/formplayer/session/FormSession.java
  src/main/java/org/commcare/formplayer/session/FormplayerInstanceInitializer.java
  src/main/java/org/commcare/formplayer/session/FormplayerSessionWrapper.java
  src/main/java/org/commcare/formplayer/session/MenuSession.java
  src/main/resources/application.properties
  src/test/java/org/commcare/formplayer/repo/EntitiesSelectionRepoTest.java
  src/test/java/org/commcare/formplayer/services/EntitiesSelectionServiceTest.java
  src/test/java/org/commcare/formplayer/services/FormSessionServiceTest.java
  src/test/java/org/commcare/formplayer/services/FormSessionsPaginationTest.java
  src/test/java/org/commcare/formplayer/tests/BaseTestClass.java
  src/test/java/org/commcare/formplayer/tests/MultiSelectCaseListTest.java
  src/test/java/org/commcare/formplayer/tests/SavedFormDefTest.java
  src/test/java/org/commcare/formplayer/utils/TestContext.java
Labels: product/invisible

#1120 Multi Select Case Lists - EOF Navigation
  src/main/java/org/commcare/formplayer/session/MenuSession.java
  src/test/java/org/commcare/formplayer/tests/MultiSelectCaseListTest.java
  src/test/resources/archives/multi_select_case_list/modules-0/forms-0.xml
  src/test/resources/archives/multi_select_case_list/modules-0/forms-1.xml
  src/test/resources/archives/multi_select_case_list/suite.xml
Labels: product/invisible

#1122 Fixes for multi select Case list
  src/main/java/org/commcare/formplayer/db/migration/V23__init_entities_selection.java
  src/main/java/org/commcare/formplayer/screens/FormplayerSyncScreen.java
  src/main/java/org/commcare/formplayer/session/MenuSession.java
  src/test/java/org/commcare/formplayer/tests/MultiSelectCaseClaimTest.java
  src/test/java/org/commcare/formplayer/tests/MultiSelectCaseListTest.java
  src/test/resources/archives/case_claim_with_multi_select/suite.xml
Labels: product/invisible

#1126 Use shared form definition from postgres
  src/main/java/org/commcare/formplayer/repo/FormDefinitionRepo.java
  src/main/java/org/commcare/formplayer/services/FormDefinitionService.java
  src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
  src/main/java/org/commcare/formplayer/services/NewFormResponseFactory.java
  src/main/java/org/commcare/formplayer/session/FormSession.java
  src/main/java/org/commcare/formplayer/session/MenuSession.java
  src/main/resources/application.properties
  src/test/java/org/commcare/formplayer/repo/FormDefinitionRepoTest.java
  src/test/java/org/commcare/formplayer/repo/FormSessionRepoTest.java
  src/test/java/org/commcare/formplayer/services/FormDefinitionServiceTest.java
  src/test/java/org/commcare/formplayer/tests/BaseTestClass.java
  src/test/java/org/commcare/formplayer/tests/HqUserDetailsServiceTests.java
  src/test/java/org/commcare/formplayer/utils/TestContext.java
Labels: product/invisible, QA Passed

#1125 Implements a generic storage to store a virtual data instance
  src/main/java/org/commcare/formplayer/application/AbstractBaseController.java
  src/main/java/org/commcare/formplayer/db/migration/V23__init_virtual_data_instance.java
  src/main/java/org/commcare/formplayer/exceptions/InstanceNotFoundException.java
  src/main/java/org/commcare/formplayer/objects/SerializableDataInstance.java
  src/main/java/org/commcare/formplayer/objects/TreeElementConverter.java
  src/main/java/org/commcare/formplayer/repo/VirtualDataInstanceRepo.java
  src/main/java/org/commcare/formplayer/services/EntitiesSelectionService.java
  src/main/java/org/commcare/formplayer/services/MenuSessionFactory.java
  src/main/java/org/commcare/formplayer/services/NewFormResponseFactory.java
  src/main/java/org/commcare/formplayer/services/ScheduledTasks.java
  src/main/java/org/commcare/formplayer/services/VirtualDataInstanceService.java
  src/main/java/org/commcare/formplayer/session/FormSession.java
  src/main/java/org/commcare/formplayer/session/FormplayerInstanceInitializer.java
  src/main/java/org/commcare/formplayer/session/FormplayerSessionWrapper.java
  src/main/java/org/commcare/formplayer/session/MenuSession.java
  src/main/java/org/commcare/formplayer/util/Constants.java
  src/main/resources/application.properties
  src/test/java/org/commcare/formplayer/repo/EntitiesSelectionRepoTest.java
  src/test/java/org/commcare/formplayer/repo/VirtualDataInstanceRepoTest.java
  src/test/java/org/commcare/formplayer/services/VirtualDataInstanceServiceTest.java
  src/test/java/org/commcare/formplayer/tests/BaseTestClass.java
  src/test/java/org/commcare/formplayer/tests/HqUserDetailsServiceTests.java
  src/test/java/org/commcare/formplayer/tests/SavedFormDefTest.java
  src/test/java/org/commcare/formplayer/utils/TestContext.java
Labels: product/invisible

#1130 Fixes user equality match
  src/main/java/org/commcare/formplayer/services/VirtualDataInstanceService.java
Labels: product/invisible

#1117 Dont sync on 204 code from case claim request
  src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
  src/main/java/org/commcare/formplayer/web/client/WebClient.java
  src/test/java/org/commcare/formplayer/tests/CaseClaimNavigationTests.java
  src/test/java/org/commcare/formplayer/tests/CaseClaimTests.java
Labels: product/feature-flag

#1136 Update staging.yaml
  scripts/staging.yaml
Labels: product/invisible
